branch-defaults:
  master:
    environment: RealEstateEvaluator-dev
    group_suffix: null
global:
  application_name: RealEstateEvaluator
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-dustin
  repository: null
  sc: git
  workspace_type: Application
